language: rust
rust:
- stable
- beta
- nightly
cache: cargo
matrix:
  allow_failures:
  - rust: nightly
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
notifications:
  email:
    recipients:
    - antoine.plaskowski@epitech.eu
    - rodolphe.roussel@epitech.eu
    on_success: change
    on_failure: always
  slack:
    secure: M/tNsrpOd9X6E0IgiIOoypENvHet45dYJMU7lvxquFg7k2RowCrIsGIhnzYf/DMpTbarqtC2bLxFZIsCw1IKudsOesozw4Ves48cZvR/7FY4lfo4tdbQOlWtMG/Z4L9jbjUrEroNcenBJH/O43cxH1lgJobQmlBnWMAyhN3SqB47RSOg2/hEwC5RW2qIOKGAD5uUwl+jt2zq4YrR5Obd90yPB8pgRza2A8+f7xOmq5uWoDGY0pA24wswGUqi95yaeud5BNjYvs+JMQj5KWF7dRMrmRQqbG9rz0Z2swEu0e6eJBZN0wN18u+a8gw2EcNzHdd9Kt/iyes2no450g4GDlCV/HKd03juKRve0gxjK3VsptS0++Zvv4kZxW6j+DvBoHoHCcZdW4OvQrlYi7WGs1Z4zMeVkKqM4jvcALG+QPx3dvo2X4YULRhoNNmo9HPYDYD3/WBGA5hVVrrRWECjL7dZQWra687o8qQDV7X63qDliBwxS/kk8TfOFZoYMnylcclwivcx/F6vBbPUXXND89JfAaiyIORUgc3qWQD6YWhlUcSR3xD4ocA+uKCS+Owc5gnbdHXlmua0mtjSjxPmofswuuEqLe90BehrKmmskrofpfXiTq0eZciX1Gx3akN23H63ynnK/MzdpHc5zKGlh9tgqYWv4n2YDeq/2yZ8uEU=
