language: rust
rust:
- stable
- beta
- nightly
cache: cargo
matrix:
  allow_failures:
  - rust: nightly
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
notifications:
  email:
    recipients:
    - antoine.plaskowski@epitech.eu
    - rodolphe.roussel@epitech.eu
    on_success: change
    on_failure: always
  slack:
    secure: GnhzXRNbXEWI01EbAWBdQwZGmaAb/A0Nb29l+n1Y1DEylqYccb6xYQ0YdM0KkFxxNpE+6hyjuq7MAHUYa2nnkRwZYAPKvoeMlmKImiHboJ0lrYnStttN6YhlhP9yEkRd2L04Cw3ySbfm0A9TUxA0/paxAFvmVVabW9cLRfwm7rSAi+Wt574XlCCaea1dX+QPNsVH8TyM4olXjXA8xAf3wsB29X12oOaIN7xz6Eibw+MtyQfsWv9frxJJhe0kcxXpyoaN3wOBOvvXY/UPt72djdr1cIPNHjBNvh5AqonrPajcsQPcrgl6+r8xTUjPOk9J+wTmmVD+h36w7ymm/UouxdceZcLDfc7PXYUFX/O6fklT5HRGL5HtRNuCqR/xFMT1yDkrUJSu0j2Er0ezuNrVzTsdl/nY839SVL3CmNrTseBI/FthgpH2bOKC19M6B1x+lA7hcvhLjrHkwGZbwix+fCSbtKLXZzh0yA2ZKck63MOkqI7V/vxv24YQcOMC1jNvKzmG+DXuXv3vLP2Ctbc0yq5XcQSrGrAZSmCm2Q0MAljl4u+o4PA9sLzyoqRAwcJ4wB+0UjM4ulaaO2SlecIM2lM4I4342oo2rhJD1cjO4CGH21SyNH7lPWbTrljKnkeJnIgNQ97lsY3WH/vUCl3CD/v3u5Fyn7IHQn+MfglGhyI=
